ARG JDK_VERSION=16-slim
FROM openjdk:${JDK_VERSION}

ARG FOLDER_NAME="papermc_server"
ENV FOLDER_NAME "$FOLDER_NAME"
ARG PROJECT_NAME="paper"
ENV PROJECT_NAME "$PROJECT_NAME"
ARG MINECRAFT_VERSION=""
ENV MINECRAFT_VERSION "$MINECRAFT_VERSION"
ARG PAPERMC_VERSION="latest"
ENV PAPERMC_VERSION "$PAPERMC_VERSION"
ARG RAM="1024MB"
ENV RAM "$RAM"
ARG JAVA_ARGS=""
ENV JAVA_ARGS "$JAVA_ARGS"

RUN apt-get update
RUN apt-get install -y wget

COPY setup.sh ./
RUN chmod +x ./setup.sh
CMD ["./setup.sh"]

VOLUME "$FOLDER_NAME"
EXPOSE 25565/tcp
EXPOSE 25565/udp
